#!/bin/bash
#
# vpn_router_up.sh
# Turn this Mac into a dual-Ethernet VPN router using:
#  - WAN:  ISP router → en6
#  - LAN:  LAN clients (2nd Mac / future router) → en5
#  - VPN:  Sing-box TUN (utunX)
#
# Assumes:
#  - Sing-box TUN is already running
#  - dnsmasq installed via Homebrew

set -e

echo "=== VPN Router UP (dual USB-Ethernet RJ45 adapters) ==="

# Interfaces (EDIT THESE LINES TO MATCH YOUR SYSTEM)
WAN_IF="en6"                 # to ISP router
LAN_IF="en5"                 # to your LAN / router WAN

# LAN network
LAN_IP="192.168.50.1"
LAN_NETMASK="255.255.255.0"  # MUST be /24
LAN_CIDR="192.168.50.0/24"

# dnsmasq paths (Homebrew default)
DNSMASQ_MAIN="/usr/local/etc/dnsmasq.conf"
DNSMASQ_MAIN_BAK="/usr/local/etc/dnsmasq.conf.vpnrouter.bak"
DNSMASQ_DIR="/usr/local/etc/dnsmasq.d"
DNSMASQ_LAN_CONF="$DNSMASQ_DIR/lan-dhcp.conf"

# pf backup
PF_BACKUP="/etc/pf.conf.vpnrouter.bak"

#############################################
# 1) Detect VPN utun interface
VPN_IF=$(ifconfig | grep -oE 'utun[0-9]+' | head -n 1 || true)

if [ -z "$VPN_IF" ]; then
  echo "ERROR: no utun interface found."
  echo "Start sing-box in TUN mode first, then run this script."
  exit 1
fi

echo "Detected VPN interface: $VPN_IF"
echo "WAN: $WAN_IF  LAN: $LAN_IF"

#############################################
# 2) Give LAN interface a static IP
echo "Configuring LAN interface $LAN_IF as $LAN_IP/$LAN_NETMASK ..."

sudo ifconfig "$LAN_IF" inet "$LAN_IP" netmask "$LAN_NETMASK"

echo "Current $LAN_IF addresses:"
ifconfig "$LAN_IF" | sed -n '1,6p'
echo

#############################################
# 3) Enable IPv4 forwarding (runtime only)
echo "Enabling IPv4 forwarding ..."
sudo sysctl -w net.inet.ip.forwarding=1 >/dev/null 2>&1 || true
# Disable legacy ipfw firewall if present (we use pf)
sudo sysctl -w net.inet.ip.fw.enable=0 >/dev/null 2>&1 || true

#############################################
# 4) Ensure dnsmasq installed via Homebrew
if ! command -v brew >/dev/null 2>&1; then
  echo "ERROR: Homebrew not found; dnsmasq must be installed via brew."
  exit 1
fi

if ! command -v dnsmasq >/dev/null 2>&1; then
  echo "dnsmasq not found. Installing with Homebrew..."
  brew install dnsmasq
fi

#############################################
# 5) Backup original dnsmasq.conf (once) and write our config
echo "Preparing dnsmasq configuration ..."

# Backup existing main dnsmasq config, if any and backup not yet made
if [ -f "$DNSMASQ_MAIN" ] && [ ! -f "$DNSMASQ_MAIN_BAK" ]; then
  echo "Backing up $DNSMASQ_MAIN to $DNSMASQ_MAIN_BAK ..."
  sudo cp "$DNSMASQ_MAIN" "$DNSMASQ_MAIN_BAK"
elif [ -f "$DNSMASQ_MAIN_BAK" ]; then
  echo "dnsmasq main backup $DNSMASQ_MAIN_BAK already exists; not overwriting."
fi

# Ensure directory exists
sudo mkdir -p "$DNSMASQ_DIR"

# Main dnsmasq config: include per-interface files
echo "Writing main dnsmasq config: $DNSMASQ_MAIN ..."
sudo tee "$DNSMASQ_MAIN" >/dev/null <<EOF
# Main dnsmasq config (Homebrew)
# Load all per-interface configs from $DNSMASQ_DIR
conf-dir=$DNSMASQ_DIR,*.conf
EOF

# LAN DHCP config
echo "Writing dnsmasq LAN DHCP config: $DNSMASQ_LAN_CONF ..."
sudo tee "$DNSMASQ_LAN_CONF" >/dev/null <<EOF
# DHCP for VPN-router LAN (generated by vpn_router_up.sh)

interface=$LAN_IF
bind-interfaces

# DHCP range on $LAN_CIDR
dhcp-range=192.168.50.10,192.168.50.100,12h

# Default gateway (this Mac)
dhcp-option=3,$LAN_IP

# DNS (public; can later switch to tunnel DNS)
dhcp-option=6,1.1.1.1
EOF

echo "Restarting dnsmasq via Homebrew..."
sudo brew services restart dnsmasq || sudo brew services start dnsmasq

echo "Checking that dnsmasq is listening on DHCP (UDP 67)..."
if sudo lsof -iUDP:67 | grep -q dnsmasq; then
  echo "OK: dnsmasq is providing DHCP on UDP 67."
else
  echo "WARNING: dnsmasq is NOT listening on UDP 67. DHCP may not work."
fi
echo

#############################################
# 6) Backup original pf.conf once
if [ ! -f "$PF_BACKUP" ]; then
  echo "Backing up /etc/pf.conf to $PF_BACKUP ..."
  sudo cp /etc/pf.conf "$PF_BACKUP"
else
  echo "Backup $PF_BACKUP already exists; not overwriting."
fi

#############################################
# 7) Write new pf.conf with VPN NAT
echo "Writing /etc/pf.conf with VPN NAT rules ..."

sudo tee /etc/pf.conf >/dev/null <<EOF
# pf.conf for dual-Ethernet VPN router
# WAN: $WAN_IF
# LAN: $LAN_IF
# VPN: $VPN_IF

set skip on lo0

# --- Translation (NAT) must come before filter rules ---

# NAT LAN -> VPN tunnel (kill-switch: no NAT to WAN)
nat on $VPN_IF from $LAN_IF:network to any -> ($VPN_IF)

# --- Filtering rules ---

# Allow Mac's own traffic on WAN and VPN
pass out quick on $WAN_IF inet from any to any keep state
pass out quick on $VPN_IF inet from any to any keep state

# Allow LAN clients to go through VPN
pass in  quick on $LAN_IF inet from $LAN_CIDR to any keep state
pass out quick on $VPN_IF inet from $LAN_CIDR to any keep state

# Allow management of LAN IP (e.g. your router talking to $LAN_IP)
pass in  quick on $LAN_IF inet from $LAN_CIDR to $LAN_IP keep state
pass out quick on $LAN_IF inet from $LAN_IP to $LAN_CIDR keep state
EOF

echo "Reloading pf rules and enabling pf..."
sudo pfctl -f /etc/pf.conf
sudo pfctl -e

echo
echo "=== VPN router mode is UP ==="
echo "Now:"
echo "  1) Ensure Sing-box TUN is running (it already should be)."
echo "  2) Plug ISP router -> $WAN_IF"
echo "  3) Plug your own router or 2nd Mac -> $LAN_IF"
echo "  4) Set that device's interface to DHCP."
echo
echo "Useful checks:"
echo "  ifconfig $LAN_IF          # should show $LAN_IP/24"
echo "  sudo lsof -iUDP:67        # dnsmasq DHCP"
echo "  sudo pfctl -s nat"
echo "  sudo pfctl -s rules | head -n 30"
echo
echo "On a client behind this Mac, run:  curl https://ifconfig.io/ip  — should show VPN exit IP."
