#!/bin/bash
#
# vpn_router_setup.sh
# One-time "slow" setup for vpnrd:
#  - Configure LAN IP
#  - Enable forwarding
#  - Configure dnsmasq DHCP
#  - Install pf anchor structure (base + vpn anchors)
#
# Recovery should NOT call this. Recovery should call vpn_router_pf_apply.sh.

set -e

echo "=== VPN Router SETUP (slow) ==="

# Interfaces (EDIT THESE LINES TO MATCH YOUR SYSTEM)
WAN_IF="${1:-en5}"   # to ISP router
LAN_IF="${2:-en8}"   # to your LAN / downstream router WAN

# LAN network
LAN_IP="192.168.50.1"
LAN_NETMASK="255.255.255.0"  # MUST be /24
LAN_CIDR="192.168.50.0/24"

# dnsmasq paths (Homebrew default)
DNSMASQ_MAIN="/usr/local/etc/dnsmasq.conf"
DNSMASQ_MAIN_BAK="/usr/local/etc/dnsmasq.conf.vpnrouter.bak"
DNSMASQ_DIR="/usr/local/etc/dnsmasq.d"
DNSMASQ_LAN_CONF="$DNSMASQ_DIR/lan-dhcp.conf"

# pf backup + anchors
PF_BACKUP="/etc/pf.conf.vpnrouter.bak"
PF_ANCHOR_DIR="/etc/pf.anchors"
PF_ANCHOR_BASE="$PF_ANCHOR_DIR/vpnrd_base"
PF_ANCHOR_VPN="$PF_ANCHOR_DIR/vpnrd_vpn"

echo "WAN: $WAN_IF  LAN: $LAN_IF"
echo "LAN: $LAN_CIDR  (router IP: $LAN_IP)"

#############################################
# 1) Give LAN interface a static IP
echo "Configuring LAN interface $LAN_IF as $LAN_IP/$LAN_NETMASK ..."
sudo ifconfig "$LAN_IF" inet "$LAN_IP" netmask "$LAN_NETMASK"

echo "Current $LAN_IF addresses:"
ifconfig "$LAN_IF" | sed -n '1,6p'
echo

#############################################
# 2) Enable IPv4 forwarding (runtime only)
echo "Enabling IPv4 forwarding ..."
sudo sysctl -w net.inet.ip.forwarding=1 >/dev/null 2>&1 || true
sudo sysctl -w net.inet.ip.fw.enable=0 >/dev/null 2>&1 || true

#############################################
# 3) Ensure dnsmasq installed via Homebrew
if ! command -v brew >/dev/null 2>&1; then
  echo "ERROR: Homebrew not found; dnsmasq must be installed via brew."
  exit 1
fi

if ! command -v dnsmasq >/dev/null 2>&1; then
  echo "dnsmasq not found. Installing with Homebrew..."
  brew install dnsmasq
fi

#############################################
# 4) Backup original dnsmasq.conf (once) and write our config
echo "Preparing dnsmasq configuration ..."

if [ -f "$DNSMASQ_MAIN" ] && [ ! -f "$DNSMASQ_MAIN_BAK" ]; then
  echo "Backing up $DNSMASQ_MAIN to $DNSMASQ_MAIN_BAK ..."
  sudo cp "$DNSMASQ_MAIN" "$DNSMASQ_MAIN_BAK"
elif [ -f "$DNSMASQ_MAIN_BAK" ]; then
  echo "dnsmasq main backup $DNSMASQ_MAIN_BAK already exists; not overwriting."
fi

sudo mkdir -p "$DNSMASQ_DIR"

echo "Writing main dnsmasq config: $DNSMASQ_MAIN ..."
sudo tee "$DNSMASQ_MAIN" >/dev/null <<EOF
# Main dnsmasq config (Homebrew)
# Load all per-interface configs from $DNSMASQ_DIR
conf-dir=$DNSMASQ_DIR,*.conf
EOF

echo "Writing dnsmasq LAN DHCP config: $DNSMASQ_LAN_CONF ..."
sudo tee "$DNSMASQ_LAN_CONF" >/dev/null <<EOF
# DHCP for VPN-router LAN (generated by vpn_router_setup.sh)

interface=$LAN_IF
bind-interfaces

# DHCP range on $LAN_CIDR
dhcp-range=192.168.50.10,192.168.50.100,12h

# Default gateway (this Mac)
dhcp-option=3,$LAN_IP

# DNS (public; can later switch to tunnel DNS)
dhcp-option=6,1.1.1.1
EOF

echo "Restarting dnsmasq via Homebrew..."
sudo brew services restart dnsmasq || sudo brew services start dnsmasq

echo "Checking that dnsmasq is listening on DHCP (UDP 67)..."
if sudo lsof -iUDP:67 | grep -q dnsmasq; then
  echo "OK: dnsmasq is providing DHCP on UDP 67."
else
  echo "WARNING: dnsmasq is NOT listening on UDP 67. DHCP may not work."
fi
echo

#############################################
# 5) Backup /etc/pf.conf once
if [ ! -f "$PF_BACKUP" ]; then
  echo "Backing up /etc/pf.conf to $PF_BACKUP ..."
  sudo cp /etc/pf.conf "$PF_BACKUP"
else
  echo "Backup $PF_BACKUP already exists; not overwriting."
fi

#############################################
# 6) Install pf anchors (base + vpn)
echo "Installing pf anchor files in $PF_ANCHOR_DIR ..."

# Base anchor: stable rules (no utun dependency)
sudo tee "$PF_ANCHOR_BASE" >/dev/null <<EOF
# vpnrd_base (stable)
# WAN: $WAN_IF
# LAN: $LAN_IF
# LAN CIDR: $LAN_CIDR
# LAN IP: $LAN_IP

set skip on lo0
scrub in all fragment reassemble

# LAN DHCP + local LAN traffic (same as now)
pass out quick on $LAN_IF inet proto udp from $LAN_IP port 67 to any port 68 keep state
pass out quick on $LAN_IF inet from $LAN_IP to $LAN_CIDR flags S/SA keep state
pass in  quick on $LAN_IF inet from $LAN_CIDR to $LAN_IP flags S/SA keep state
pass in  quick on $LAN_IF proto udp from any port 68 to any port 67 keep state

# Kill-switch: block LAN subnet from reaching WAN directly
block drop out quick on $WAN_IF inet from $LAN_CIDR to any
EOF

# VPN anchor: will be rewritten fast by vpn_router_pf_apply.sh
sudo tee "$PF_ANCHOR_VPN" >/dev/null <<EOF
# vpnrd_vpn (DYNAMIC)
# This file is rewritten by vpn_router_pf_apply.sh
# Placeholder only.
EOF

#############################################
# 7) Write /etc/pf.conf once to load our anchors
echo "Writing /etc/pf.conf to load vpnrd anchors ..."

sudo tee /etc/pf.conf >/dev/null <<EOF
# pf.conf managed by vpnrd (dual-Ethernet VPN router)
# WAN: $WAN_IF
# LAN: $LAN_IF
# Anchors:
#   - vpnrd/base (stable)
#   - vpnrd/vpn  (dynamic; utun-specific)

anchor "vpnrd/base"
load anchor "vpnrd/base" from "$PF_ANCHOR_BASE"

anchor "vpnrd/vpn"
load anchor "vpnrd/vpn" from "$PF_ANCHOR_VPN"
EOF

echo "Reloading pf rules and enabling pf..."
sudo pfctl -f /etc/pf.conf

if ! sudo pfctl -s info 2>/dev/null | grep -q "Status: Enabled"; then
  sudo pfctl -e
else
  echo "pf already enabled; skipping pfctl -e"
fi

echo
echo "=== VPN Router SETUP complete ==="
echo "Next: call vpn_router_pf_apply.sh with the current utunX and server allowlist."

